# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.org2.jwclab.com:

networks:
  test:

services:
  
  peer0.org2.jwclab.com:
    container_name: peer0.org2.jwclab.com
    image: hyperledger/fabric-peer:2.2.0
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/org2/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/org2/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/org2/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.org2.jwclab.com
      - CORE_PEER_ADDRESS=peer0.org2.jwclab.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.jwclab.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.jwclab.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.jwclab.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../jwclab-network/org2_peer_org_crypto/peers/peer0.org2.jwclab.com/msp:/var/hyperledger/org2/msp
        - ../jwclab-network/org2_peer_org_crypto/peers/peer0.org2.jwclab.com/tls:/var/hyperledger/org2/tls
        - peer0.org2.jwclab.com:/var/hyperledger/production
    working_dir: /var/hyperledger
    command: peer node start
    ports:
      - 9051:9051
    networks:
      - test